### ISSUE TITLE
DP: BLOCKED TLS proxy server configurations

### ISSUE THREAD

**Issue by gaukas** [gaukas/gfw-tls-2022-oct#2]
This issue is to collect DPs for the configuration/setups for TLS proxy servers that are getting blocked.

Please do not post discussions in the reply. Instead, all discussions should go into #1. 

### Minimal Checklist
- ISP/IDC 
    - e.g., `DigitalOcean San Francisco`, `AWS Lightsail Japan`
- Protocol 
    - e.g., `V2Ray`, `Trojan`, `Trojan-go`, `NaiveProxy`(likely no?), etc
- Optional Features/Extensions/Plugins
    - e.g., `Websocket`, `Mux`, `Reuse Session/Port`, `Shadowsocks Transport`, etc

### Additional Info You May Include
- IP Lifespan (for how long the blocked IP was used for TLS circumvention)
- Blocked since and how
- Estimated active user count and/or bandwidth (GB/day)
- Complete list of clients used (e.g. `Shadowrocket`, `V2rayN`, etc) to connect to the proxy. Attach the TLS ClientHello fingerprint hash if possible.
    - https://tlsfingerprint.io/

----

本 issue 用以收集已被阻断的 TLS 代理服务器配置的数据点。

请不要在回复中发表讨论。请去 #1 讨论。

### 最小检查单
- 服务提供商/数据中心
    - 如，`Digital Ocean San Francisco`, `AWS Lightsail Japan`
- 协议
    - 如，`V2Ray`, `Trojan`, `Trojan-go`, `NaiveProxy`(好像没有？) 等
- 可选特性/扩展/外挂
    - 如，`Websocket`, `Mux`, `Reuse Session/Port`, `Shadowsocks Transport` 等

### 可以包含的额外信息
- IP 寿命（被阻断的IP被用于TLS规避多久）
- 自何时起被阻断，以及如何阻断
- 估计活跃用户数和/或带宽（GB 每日）
- 完整的客户使用（如，`Shadowrocket`, `V2rayN`, 等）以连接到代理。随附 TLS ClientHello 指纹如有可能。
    - https://tlsfingerprint.io/

**Comment by gaukas** [comment]
ISP/IDC: DMIT
Protocol: V2Ray
Features/Extensions/Plugins: TLS+Websocket
Client ISP: China Telecom Ethernet, China Unicom Cellular 5G
Client Geolocation: Lu'an, Anhui, China

----

Source: https://github.com/net4people/bbs/issues/129#issuecomment-1272217635

**Comment by gaukas** [comment]
ISP/IDC: Gigsgigscloud
Protocol: Trojan/NaiveProxy
Features/Extensions/Plugins: N/A
Client ISP: China Telecom Ethernet, China Unicom Cellular 5G
Client Geolocation: Lu'an, Anhui, China

----

Source: https://github.com/net4people/bbs/issues/129#issuecomment-1272217635

**Comment by rfbzs** [comment]
- Server information
  - IDC: AWS Lightsail
  - Protocol: Trojan
  - Implementation tool: Trojan-go with default configuration
  - Features/extensions/plugins: N/A
  - Backend for website masquerading: nginx
- Client information
  - ISP: China Telecom
  - Client tool: Clash
- Other information
  - Newly deployed server on 2022-10-06, survived for 6~12 hours
  - One active client with total traffic less than 1GB

**Comment by rfbzs** [comment]
- Server information
  - IDC: AWS Lightsail
  - Protocol: Trojan
  - Implementation tool: Trojan-go with default configuration
  - Features/extensions/plugins: N/A
  - Backend for website masquerading: nginx
- Client information
  - ISP: China Telecom
  - Client tool: Clash
- Other information
  - Newly deployed server on 2022-10-07, survived for 6~12 hours
  - One active client with total traffic less than 1GB
  - Server used a firewall to allow connections only from specific IP addresses
