### ISSUE TITLE
DP: SURVIVING TLS proxy server configurations

### ISSUE THREAD

**Issue by gaukas** [gaukas/gfw-tls-2022-oct#3]
This issue is to collect DPs for the configuration/setups for TLS proxy servers that are not getting blocked so far.

Please do not post discussions in the reply. Instead, all discussions should go into #1. 

### Minimal Checklist
- ISP/IDC 
    - e.g., `DigitalOcean San Francisco`, `AWS Lightsail Japan`
- Protocol 
    - e.g., `V2Ray`, `Trojan`, `Trojan-go`, `NaiveProxy`, etc
- Optional Features/Extensions/Plugins
    - e.g., `Websocket`, `Mux`, `Reuse Session/Port`, `Shadowsocks Transport` etc

### Additional Info You May Include
- IP Lifespan (for how long the surviving IP was used for TLS circumvention)
- Estimated active user and/or bandwidth (GB/day)
- Full list of clients (e.g. `Shadowrocket`, `V2rayN`, etc) used to connect to the proxy. Attach the TLS ClientHello fingerprint hash if possible.
    - https://tlsfingerprint.io/

----

本 issue 用以收集仍未被阻断的 TLS 代理服务器配置的数据点。

请不要在回复中发表讨论。请去 #1 讨论。

### 最小检查单
- 服务提供商/数据中心
    - 如，`Digital Ocean San Francisco`, `AWS Lightsail Japan`
- 协议
    - 如，`V2Ray`, `Trojan`, `Trojan-go`, `NaiveProxy` 等
- 可选特性/扩展/外挂
    - 如，`Websocket`, `Mux`, `Reuse Session/Port`, `Shadowsocks Transport` 等

### 可以包含的额外信息
- IP 寿命（IP已被用于TLS规避多久）
- 估计活跃用户数和/或带宽（GB 每日）
- 完整的客户使用（如，`Shadowrocket`, `V2rayN`, 等）以连接到代理。随附 TLS ClientHello 指纹如有可能。
    - https://tlsfingerprint.io/

**Comment by cross-hello** [comment]
Don't know. From the start just cling to CDN, and utls is client settings by default. 
But sometimes still can't connect to CDN(the poblem of China mobile internet only, Telecom will always ok). Doubt the problem of TLS over TLS detection.

**Comment by rfbzs** [comment]
- Server information
  - IDC: AWS Lightsail
  - Server tool: [Haproxy + Tinyproxy](https://github.com/klzgrad/naiveproxy/wiki/HAProxy-Setup)
  - Features/extensions/plugins: N/A
  - Backend for website masquerading: nginx
- Client information
  - ISP: China Telecom
  - Protocol: naiveproxy
  - Client tool: naiveproxy in windows (v106.0.5249.91-1), sagernet with naiveproxy-plugin (v106.0.5249.91-1)
- Other information
  - Newly deployed server on 2022-10-07, survived for more than 3 days.
  - One active client with daily traffic 10~500 MB

**Comment by rfbzs** [comment]
- Server information
  - IDC: AWS Lightsail
  - Protocol: Trojan
  - Implementation tool: Trojan-go with default configuration
  - Features/extensions/plugins: N/A
  - Backend for website masquerading: nginx
- Client information
  - ISP: China Telecom
  - Client tool: Trojan-go with uTLS
- Other information
  - Newly deployed server on 2022-10-08, survived for over 3 days
  - One active client with total traffic over 2 GB
